workflows:
  ios-sideload-build:
    name: iOS Sideload Build (No Code Signing)
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    triggering:
      events:
        - push
        - pull_request
        - tag

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks/
          pod repo update
          pod install

      - name: Build iOS archive (no code signing)
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/Runner.xcarchive" \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_ENTITLEMENTS="" \
            IPHONEOS_DEPLOYMENT_TARGET=16.0 \
            -v

      - name: Export IPA (sideload)
        script: |
          mkdir -p "$CM_BUILD_DIR/Payload"
          cp -r "$CM_BUILD_DIR/build/Runner.xcarchive/Products/Applications/Runner.app" "$CM_BUILD_DIR/Payload/"
          cd "$CM_BUILD_DIR"
          zip -r -q face_pixel.ipa Payload/
          rm -rf Payload
          ls -lah face_pixel.ipa

    artifacts:
      - $CM_BUILD_DIR/face_pixel.ipa
      - build/logs/flutter_build.log